export const SHOW_MENU = 'SHOW_MENU'
export const HIDE_MENU = 'HIDE_MENU'
export const SET_HEADER_CLASSES = 'SET_HEADER_CLASSES'

export const SET_SHOW_LOADER = 'SET_SHOW_LOADER'
export const SET_REMOVE_DISH = 'SET_REMOVE_DISH'
export const SET_CHANGE_QUANTITY = 'SET_CHANGE_QUANTITY'
export const SET_CHANGE_PERSONS = 'SET_CHANGE_PERSONS'

export const BASKET_REMOVE_ITEM = 'BASKET_REMOVE_ITEM'
export const BASKET_CHANGE_QUANTITY = 'BASKET_CHANGE_QUANTITY'
export const BASKET_ADD_STUFF = 'BASKET_ADD_STUFF'
export const BASKET_STUFF_QUANTITY = 'BASKET_STUFF_QUANTITY'
export const CUSTOMER_DATE = 'CUSTOMER_DATE'
export const SET_CUSTOMER_DATA = 'SET_CUSTOMER_DATA'
export const SET_VALIDATION = 'SET_VALIDATION'

export const SET_FILTERS = 'SET_FILTERS'

export const SET_CASE = 'SET_CASE'